CREATE TABLE "CUSTOMER" (
	    "ID"   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	    "NAME" VARCHAR(128) NOT NULL,
	    "PASSWORD" VARCHAR(128),
	    "EMAIL" VARCHAR(128),
	    PRIMARY KEY (id)
);

CREATE TABLE "EVENT" (
    "ID"   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "CODE" VARCHAR(128) NOT NULL,
    "TITLE" VARCHAR(128) NOT NULL,
    "DESCRIPTION" VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE "REGISTRATION" (
    "ID"   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    "EVENT_ID" INTEGER  NOT NULL,
    "CUSTOMER_ID" INTEGER NOT NULL,
    "REGISTRATION_DATE" DATE NOT NULL,
    "NOTES" VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);